spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/fastvue3}
    username: ${DATABASE_USERNAME:fastvue3}
    password: ${DATABASE_PASSWORD:fastvue3}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    com.fastvue: debug
